import "./globals.css";
import { Merriweather } from "next/font/google";
import Head from "next/head";


// Import czcionki Merriweather z Google Fonts
const merriweather = Merriweather({
    subsets: ["latin"],
    weight: ["400", "700"],
    variable: "--font-merriweather",
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
        {/* Import FreightBig z Adobe Fonts */}
        <head>
            <link
                rel="stylesheet"
                href="https://use.typekit.net/icu4qan.css"
            />
        </head>

        <body
            className={`${merriweather.variable} antialiased`}
        >
        {children}
        </body>
        </html>
    );
}
